### ISSUE TITLE
'initial-commit' tag seems missing

### ISSUE THREAD

**Issue by hurims** [vivaldi/Vivaldi-GN#2]
It seems that build/gen.py isn't working.
```
$ python build/gen.py
fatal: No names found, cannot describe anything.
Traceback (most recent call last):
  File "build/gen.py", line 652, in <module>
    sys.exit(main(sys.argv[1:]))
  File "build/gen.py", line 57, in main
    GenerateLastCommitPosition(os.path.join(out_dir, 'last_commit_position.h'))
  File "build/gen.py", line 66, in GenerateLastCommitPosition
    cwd=REPO_ROOT)
  File "C:\dev\depot_tools\win_tools-2_7_6_bin\python\bin\lib\subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', 'describe', 'HEAD', '--match', 'initial-commit']' returned non-zero exit status 128
```
The reason looks beause of the missing tag, called 'initial-commit'.

```
$ git describe HEAD --match initial-commit
fatal: No annotated tags can describe '9a3c3910e6622ecac82407d7412d887fe26b682d'.
However, there were unannotated tags: try --tags.
```

The original GN repo has the tag,  so maybe we need to create one also.
https://gn.googlesource.com/gn/+/initial-commit

After creation, build succeeded.
```
$ git tag "initial-commit" -a -m "Initial commit." -- "95374957437b818e9addc26c83340b27a1b38202"
```

**Comment by YngveNPettersen** [comment]
Have pushed that tag. Thanks for noticing it.

The implied way of using this repo (so implied I did not even think about it) was that it would be combined and merged locally with the upstream Chromium GN repository's master branch.
